CC = g++ -std=c++14
CPPFLAGS = -Og -g -Wall -I/usr/lib/llvm-6.0/include/
LDLIBS = -L/usr/lib/llvm-6.0/lib -lclang

#get_listings : clang_util.o get_listings.o

get_callgraph : clang_util.o graph.o get_callgraph.o

